[[redirects]]
  from = "/dashboard/*"
  to = "index.html"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = false
  query = {path = ":path"}
