[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/static/pages/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/static/pages/:splat"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; block-all-mixed-content; font-src 'self' https: data:; frame-ancestors 'self'; img-src 'self' data:; object-src 'none'; script-src 'self' https://js.stripe.com; style-src 'self' https: 'unsafe-inline'; upgrade-insecure-requests; connect-src https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com"
