[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/static/pages/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/static/pages/:splat"
  status = 200
  force = false
